exp_manager:
  checkpoint_callback_params:
    always_save_nemo: false
    filename: megatron_mixtral--{val_loss:.2f}-{step}-{consumed_samples}
    mode: min
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size},
      ${training.model.pipeline_model_parallel_size}}
    monitor: val_loss
    save_nemo_on_train_end: false
    save_top_k: 10
  create_checkpoint_callback: true
  create_wandb_logger: false
  exp_dir: null
  explicit_log_dir: ${training.run.results_dir}/results
  log_step_timing: true
  name: megatron_mixtral
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  step_timing_kwargs:
    buffer_size: 5
    sync_cuda: true
  wandb_logger_kwargs:
    name: ${training.run.name}
    project: nemo_mixtral_pretrain
model:
  activation: fast-swiglu
  activations_checkpoint_granularity: null
  activations_checkpoint_layers_per_pipeline: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  apex_transformer_log_level: 30
  apply_query_key_layer_scaling: false
  apply_rope_fusion: true
  attention_dropout: 0.0
  attention_type: multihead
  batch_p2p_comm: true
  bias: false
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  data:
    data_impl: mmap
    data_prefix:
    - 0.0333
    - ${data_dir}/my-mixtral_00_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_01_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_02_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_03_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_04_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_05_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_06_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_07_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_08_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_09_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_10_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_11_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_12_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_13_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_14_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_15_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_16_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_17_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_18_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_19_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_20_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_21_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_22_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_23_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_24_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_25_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_26_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_27_text_document
    - 0.0333
    - ${data_dir}/my-mixtral_28_text_document
    - 0.0334
    - ${data_dir}/my-mixtral_29_text_document
    dataloader_type: single
    eod_mask_loss: false
    index_mapping_dir: null
    num_workers: 2
    reset_attention_mask: false
    reset_position_ids: false
    seq_length: 4096
    skip_warmup: true
    splits_string: 99990,8,2
  do_layer_norm_weight_decay: false
  encoder_seq_length: 4096
  expert_model_parallel_size: 1
  ffn_dropout: 0
  ffn_hidden_size: 14336
  fp16_lm_cross_entropy: false
  fp32_residual_connection: false
  fp8: false
  fp8_amax_compute_algo: max
  fp8_amax_history_len: 1024
  fp8_e4m3: false
  fp8_hybrid: true
  fp8_interval: 1
  fp8_margin: 0
  gc_interval: 0
  get_attention_mask_from_fusion: true
  global_batch_size: 256
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: false
  gradient_as_bucket_view: true
  headscale: false
  hidden_dropout: 0.0
  hidden_size: 4096
  hysteresis: 2
  init_method_std: 0.02
  kv_channels: null
  layernorm_epsilon: 1.0e-05
  make_vocab_size_divisible_by: 128
  masked_softmax_fusion: false
  max_position_embeddings: 32768
  mcore_customization_config:
    new_decoder_architecture: false
    parallel_attention: false
  mcore_gpt: true
  megatron_amp_O2: true
  micro_batch_size: 1
  moe_aux_loss_coeff: 0.01
  moe_grouped_gemm: true
  moe_router_topk: 2
  moe_token_dispatcher_type: alltoall
  native_amp_growth_interval: 1000
  native_amp_init_scale: 4294967296
  normalization: rmsnorm
  normalize_attention_scores: true
  nsys_profile:
    enabled: false
    end_step: 10
    gen_shape: false
    ranks:
    - 0
    start_step: 10
  num_attention_heads: 32
  num_layers: 32
  num_micro_batches_with_partial_activation_checkpoints: null
  num_moe_experts: 8
  num_query_groups: 8
  onnx_safe: false
  openai_gelu: false
  optim:
    betas:
    - 0.9
    - 0.95
    lr: 0.0001
    name: distributed_fused_adam
    sched:
      constant_steps: 11873
      min_lr: 1.0e-05
      name: CosineAnnealing
      warmup_steps: 636
    weight_decay: 0.1
  overlap_p2p_comm: false
  persist_layer_norm: true
  pipeline_model_parallel_size: 1
  position_embedding_type: rope
  post_process: true
  pre_process: true
  precision: bf16
  rampup_batch_size: null
  reduce_amax: true
  resume_from_checkpoint: null
  rotary_base: 1000000.0
  rotary_percentage: 1.0
  seed: 1234
  seq_len_interpolation_factor: null
  sequence_parallel: true
  share_embeddings_and_output_weights: false
  sync_batch_comm: false
  tensor_model_parallel_size: 2
  tokenizer:
    library: huggingface
    type: mistralai/Mixtral-8x7B-v0.1
    use_fast: true
  transformer_block_type: pre_ln
  transformer_engine: true
  ub_tp_comm_overlap: false
  ub_tp_comm_overlap_cfg: null
  use_cpu_initialization: false
  use_emha: false
  use_flash_attention: true
  use_scaled_init_method: true
  virtual_pipeline_model_parallel_size: null
run:
  dependency: singleton
  name: mixtral_7b_8nodes_tp_2_pp_1_mbs_1_act_ckpt_None_num_mbs_act_None_act_per_pipe_None
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-0:30:00
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  enable_checkpointing: false
  gradient_clip_val: 1.0
  limit_test_batches: 1
  limit_val_batches: 1
  log_every_n_steps: 1
  logger: false
  max_epochs: null
  max_steps: 50
  max_time: '5:23:30:00'
  num_nodes: 8
  precision: bf16
  use_distributed_sampler: false
  val_check_interval: 50
