exp_manager:
  checkpoint_callback_params:
    always_save_nemo: false
    filename: megatron_t5--{val_loss:.2f}-{step}-{consumed_samples}
    mode: min
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size},
      ${training.model.pipeline_model_parallel_size}}
    monitor: val_loss
    save_nemo_on_train_end: false
    save_top_k: 10
  create_checkpoint_callback: true
  create_wandb_logger: false
  exp_dir: null
  explicit_log_dir: ${training.run.results_dir}/results
  log_step_timing: true
  name: megatron_t5
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  step_timing_kwargs:
    buffer_size: 5
    sync_cuda: true
  wandb_logger_kwargs:
    name: ${training.run.name}
    project: nemo_t5
model:
  apex_transformer_log_level: 30
  data:
    data_impl: mmap
    data_prefix:
    - 1.0
    - ${data_dir}/my-t5_00_text_document
    dataloader_type: single
    dataset_type: t5
    favor_longer_ngrams: false
    geometric_dist: true
    index_mapping_dir: null
    masked_lm_prob: 0.15
    max_ngram_size: 10
    mean_ngram_size: null
    num_workers: 4
    permutation: false
    respect_document_boundaries: true
    seq_length: 512
    seq_length_dec: 128
    short_seq_prob: 0.0
    skip_warmup: true
    splits_string: 90,5,5
    whole_word_masking: true
  decoder:
    activation: geglu
    activations_checkpoint_granularity: full
    activations_checkpoint_method: block
    activations_checkpoint_num_layers: 0
    apply_query_key_layer_scaling: true
    arch: transformer
    attention_dropout: 0.1
    bias: true
    bias_activation_fusion: true
    bias_dropout_add_fusion: true
    ffn_hidden_size: 2048
    fp32_residual_connection: false
    grad_div_ar_fusion: true
    headscale: false
    hidden_dropout: 0.1
    hidden_size: 768
    init_method_std: 0.015
    kv_channels: 64
    layernorm_epsilon: 1e-5
    masked_softmax_fusion: true
    normalization: layernorm
    num_attention_heads: 12
    num_layers: 12
    onnx_safe: false
    openai_gelu: false
    persist_layer_norm: true
    position_embedding_type: learned_absolute
    relative_attention_max_distance: 128
    relative_attention_num_buckets: 32
    relative_position_bias_self_attention_only: true
    transformer_block_type: pre_ln
  encoder:
    activation: geglu
    activations_checkpoint_granularity: full
    activations_checkpoint_method: block
    activations_checkpoint_num_layers: 0
    apply_query_key_layer_scaling: true
    arch: transformer
    attention_dropout: 0.1
    bias: true
    bias_activation_fusion: true
    bias_dropout_add_fusion: true
    ffn_hidden_size: 2048
    fp32_residual_connection: false
    grad_div_ar_fusion: true
    headscale: false
    hidden_dropout: 0.1
    hidden_size: 768
    init_method_std: 0.015
    kv_channels: 64
    layernorm_epsilon: 1e-5
    masked_softmax_fusion: true
    normalization: layernorm
    num_attention_heads: 12
    num_layers: 12
    onnx_safe: false
    openai_gelu: false
    persist_layer_norm: true
    position_embedding_type: learned_absolute
    relative_attention_max_distance: 128
    relative_attention_num_buckets: 32
    relative_position_bias_self_attention_only: true
    transformer_block_type: pre_ln
  fp16_lm_cross_entropy: false
  global_batch_size: 2048
  grad_allreduce_chunk_size_mb: 125
  gradient_as_bucket_view: true
  init_method_std: 0.015
  make_vocab_size_divisible_by: 128
  max_position_embeddings: ${.seq_length}
  megatron_amp_O2: true
  micro_batch_size: 64
  native_amp_growth_interval: 1000
  native_amp_init_scale: 4294967296
  nsys_profile:
    enabled: false
    end_step: 10
    gen_shape: false
    ranks:
    - 0
    start_step: 10
    trace:
    - nvtx
    - cuda
  optim:
    betas:
    - 0.9
    - 0.999
    bucket_cap_mb: ${training.model.grad_allreduce_chunk_size_mb}
    eps: 1e-8
    lr: 0.0001
    name: distributed_fused_adam
    overlap_grad_sync: false
    sched:
      last_epoch: -1
      min_lr: 1.0e-05
      name: WarmupAnnealing
      warmup_ratio: 0.01
    weight_decay: 0.01
  pipeline_model_parallel_size: 1
  pipeline_model_parallel_split_rank: ${divide_floor:${.pipeline_model_parallel_size},
    2}
  post_process: true
  pre_process: true
  resume_from_checkpoint: null
  seed: 1234
  seq_length: 512
  share_decoder_tokens_head_embeddings: true
  share_token_embeddings: true
  sync_batch_comm: false
  tensor_model_parallel_size: 1
  tokenizer:
    library: megatron
    merge_file: null
    model: null
    num_sentinel_tokens: 100
    type: BertWordPieceCase
    vocab_file: ${data_dir}/bpe/vocab.txt
  use_cpu_initialization: false
name: megatron_t5
restore_from_path: null
run:
  dependency: singleton
  name: t5_0.22b_4nodes_tp_1_pp_1_cp_None_ep_None_mbs_64_act_ckpt_0_num_mbs_act_None_act_per_pipe_None
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-0:10:00
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  enable_checkpointing: false
  gradient_clip_val: 1.0
  limit_test_batches: 1
  limit_val_batches: 1
  log_every_n_steps: 1
  logger: false
  max_epochs: null
  max_steps: 50
  max_time: '3:23:30:00'
  num_nodes: 4
  precision: bf16
  use_distributed_sampler: false
  val_check_interval: 50
