exp_manager:
  checkpoint_callback_params:
    always_save_nemo: false
    filename: megatron_gpt--{val_loss:.2f}-{step}-{consumed_samples}
    mode: min
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size},
      ${training.model.pipeline_model_parallel_size}}
    monitor: val_loss
    save_nemo_on_train_end: false
    save_top_k: 10
  create_checkpoint_callback: true
  create_wandb_logger: false
  exp_dir: null
  explicit_log_dir: ${training.run.results_dir}/results
  log_step_timing: true
  name: megatron_gpt
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  step_timing_kwargs:
    buffer_size: 5
    sync_cuda: true
  wandb_logger_kwargs:
    name: ${training.run.name}
    project: nemo_gpt3
model:
  activations_checkpoint_granularity: null
  activations_checkpoint_layers_per_pipeline: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  apex_transformer_log_level: 30
  apply_query_key_layer_scaling: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  data:
    data_impl: mmap
    data_prefix:
    - 1.0
    - ${data_dir}/my-gpt3_00_text_document
    dataloader_type: single
    eod_mask_loss: false
    index_mapping_dir: null
    num_workers: 2
    reset_attention_mask: false
    reset_position_ids: false
    seq_length: 2048
    skip_warmup: true
    splits_string: 99990,8,2
  encoder_seq_length: 2048
  ffn_hidden_size: ${multiply:4, ${.hidden_size}}
  fp16_lm_cross_entropy: false
  fp32_residual_connection: false
  fp8: false
  fp8_amax_compute_algo: max
  fp8_amax_history_len: 1024
  fp8_e4m3: false
  fp8_hybrid: true
  fp8_interval: 1
  fp8_margin: 0
  fp8_wgrad: true
  global_batch_size: 256
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  gradient_as_bucket_view: true
  hidden_dropout: 0.1
  hidden_size: 768
  hysteresis: 2
  init_method_std: 0.023094
  kv_channels: null
  layernorm_epsilon: 1e-5
  make_vocab_size_divisible_by: 128
  masked_softmax_fusion: true
  max_position_embeddings: 2048
  mcore_gpt: true
  megatron_amp_O2: true
  micro_batch_size: 4
  native_amp_growth_interval: 1000
  native_amp_init_scale: 4294967296
  nsys_profile:
    enabled: false
    end_step: 10
    gen_shape: false
    ranks:
    - 0
    start_step: 10
    trace:
    - nvtx
    - cuda
  num_attention_heads: 12
  num_layers: 12
  num_micro_batches_with_partial_activation_checkpoints: null
  onnx_safe: false
  optim:
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: ${training.model.grad_allreduce_chunk_size_mb}
    lr: 0.0006
    name: distributed_fused_adam
    overlap_grad_sync: false
    sched:
      constant_steps: 94985
      min_lr: 6.0e-05
      name: CosineAnnealing
      warmup_steps: 858
    weight_decay: 0.1
  persist_layer_norm: true
  pipeline_model_parallel_size: 1
  post_process: true
  pre_process: true
  resume_from_checkpoint: null
  seed: 1234
  sequence_parallel: false
  sync_batch_comm: false
  tensor_model_parallel_size: 2
  tokenizer:
    delimiter: null
    library: megatron
    merge_file: ${data_dir}/bpe/merges.txt
    model: null
    type: GPT2BPETokenizer
    vocab_file: ${data_dir}/bpe/vocab.json
  transformer_engine: false
  ub_tp_comm_overlap: false
  use_cpu_initialization: false
  virtual_pipeline_model_parallel_size: null
run:
  dependency: singleton
  name: gpt3_0.126b_8nodes_tp_2_pp_1_mbs_4_act_ckpt_None_num_mbs_act_None_act_per_pipe_None
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-0:20:00
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  enable_checkpointing: false
  gradient_clip_val: 1.0
  limit_test_batches: 1
  limit_val_batches: 1
  log_every_n_steps: 1
  logger: false
  max_epochs: null
  max_steps: 50
  max_time: '1:23:30:00'
  num_nodes: 8
  precision: bf16
  use_distributed_sampler: false
  val_check_interval: 50
