exp_manager:
  checkpoint_callback_params:
    always_save_nemo: false
    filename: megatron_bert--{val_loss:.2f}-{step}-{consumed_samples}
    mode: min
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size},
      ${training.model.pipeline_model_parallel_size}}
    monitor: val_loss
    save_top_k: 10
  create_checkpoint_callback: true
  create_wandb_logger: false
  exp_dir: null
  explicit_log_dir: ${training.run.results_dir}/results
  log_step_timing: true
  name: megatron_bert
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  step_timing_kwargs:
    buffer_size: 5
    sync_cuda: true
  wandb_logger_kwargs:
    name: ${training.run.name}
    project: nemo_bert
model:
  activations_checkpoint_granularity: null
  activations_checkpoint_layers_per_pipeline: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  apply_query_key_layer_scaling: true
  bert_binary_head: false
  data:
    data_impl: mmap
    data_prefix:
    - 1.0
    - ${data_dir}/my-t5_00_bert_tokenizer_text_document
    dataloader_type: single
    eod_mask_loss: false
    index_mapping_dir: null
    masked_lm_prob: 0.15
    num_workers: 2
    reset_attention_mask: false
    reset_position_ids: false
    seq_length: 512
    short_seq_prob: 0.1
    skip_warmup: true
    splits_string: 900,50,50
  encoder_seq_length: 512
  ffn_hidden_size: 3072
  fp16_lm_cross_entropy: false
  fp32_residual_connection: false
  global_batch_size: 256
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: false
  gradient_as_bucket_view: true
  hidden_dropout: 0.1
  hidden_size: 768
  init_method_std: 0.023094
  kv_channels: null
  layernorm_epsilon: 1e-5
  make_vocab_size_divisible_by: 128
  max_position_embeddings: ${.encoder_seq_length}
  mcore_bert: true
  megatron_amp_O2: true
  micro_batch_size: 2
  native_amp_growth_interval: 1000
  native_amp_init_scale: 4294967296
  num_attention_heads: 12
  num_layers: 12
  num_micro_batches_with_partial_activation_checkpoints: null
  onnx_safe: false
  optim:
    betas:
    - 0.9
    - 0.98
    bucket_cap_mb: ${training.model.grad_allreduce_chunk_size_mb}
    lr: 0.0002
    name: distributed_fused_adam
    overlap_grad_sync: false
    sched:
      constant_steps: 2279663
      min_lr: 2.0e-05
      name: CosineAnnealing
      warmup_steps: 20599
    weight_decay: 0.01
  pipeline_model_parallel_size: 1
  post_process: true
  pre_process: true
  seed: 1234
  sequence_parallel: false
  tensor_model_parallel_size: 2
  tokenizer:
    library: megatron
    merge_file: null
    model: null
    type: BertWordPieceLowerCase
    vocab_file: ${data_dir}/vocab.txt
  use_cpu_initialization: false
  virtual_pipeline_model_parallel_size: null
name: megatron_bert
restore_from_path: null
run:
  dependency: singleton
  name: bert_0.11b_8nodes_tp_2_pp_1_cp_None_ep_None_mbs_2_act_ckpt_None_num_mbs_act_None_act_per_pipe_None
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-0:20:00
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  enable_checkpointing: false
  gradient_clip_val: 1.0
  limit_test_batches: 1
  limit_val_batches: 1
  log_every_n_steps: 1
  logger: false
  max_epochs: -1
  max_steps: 50
  max_time: '1:23:30:00'
  num_nodes: 8
  precision: bf16
  use_distributed_sampler: false
  val_check_interval: 50
