defaults:
- _self_
- optional tp_overlap@model.ub_tp_comm_overlap_cfg: null
exp_manager:
  checkpoint_callback_params:
    always_save_nemo: false
    filename: megatron_llama--{val_loss:.2f}-{step}-{consumed_samples}
    mode: min
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size},
      ${training.model.pipeline_model_parallel_size}}
    monitor: val_loss
    save_nemo_on_train_end: false
    save_top_k: 10
  create_checkpoint_callback: true
  create_wandb_logger: false
  exp_dir: null
  explicit_log_dir: ${training.run.results_dir}/results
  log_step_timing: true
  name: megatron_llama
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  seconds_to_sleep: 60
  step_timing_kwargs:
    buffer_size: 5
    sync_cuda: true
  wandb_logger_kwargs:
    name: ${training.run.name}
    project: nemo_llama_pretrain
hydra:
  searchpath:
  - file:///opt/NeMo/examples/nlp/language_modeling/conf
model:
  activation: fast-swiglu
  activations_checkpoint_granularity: null
  activations_checkpoint_layers_per_pipeline: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  apex_transformer_log_level: 30
  apply_query_key_layer_scaling: true
  apply_rope_fusion: true
  attention_dropout: 0.0
  attention_type: multihead
  bias: false
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  context_parallel_size: 1
  cross_entropy_loss_fusion: true
  data:
    data_impl: mmap
    data_prefix:
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_01_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_02_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_03_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_04_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_05_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_06_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_07_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_08_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_09_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_10_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_11_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_12_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_head_gopher_linefilter_decompressed/bin_idx/nemo/head_13_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_01_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_02_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_03_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_04_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_05_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_06_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_07_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_08_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_09_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_10_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_11_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_12_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_13_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_14_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_15_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_16_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_17_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_18_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_19_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_20_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_21_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_22_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_23_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_24_text_document
    - 0.0263
    - ${data_dir}/kenlm_perp_middle_gopher_linefilter_decompressed/bin_idx/nemo/middle_25_text_document
    dataloader_type: single
    eod_mask_loss: false
    index_mapping_dir: null
    num_workers: 2
    reset_attention_mask: false
    reset_position_ids: false
    seq_length: 8192
    skip_warmup: true
    splits_string: 99990,8,2
  do_layer_norm_weight_decay: false
  encoder_seq_length: 8192
  expert_model_parallel_size: 1
  ffn_dropout: 0.0
  ffn_hidden_size: 14336
  fp16_lm_cross_entropy: false
  fp32_residual_connection: false
  fp8: false
  fp8_amax_compute_algo: max
  fp8_amax_history_len: 1024
  fp8_e4m3: false
  fp8_hybrid: false
  fp8_interval: 1
  fp8_margin: 0
  gc_interval: 100
  global_batch_size: 2048
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  gradient_as_bucket_view: true
  headscale: false
  hidden_dropout: 0.0
  hidden_size: 4096
  hysteresis: 2
  init_method_std: 0.01
  kv_channels: null
  layernorm_epsilon: 1.0e-05
  make_vocab_size_divisible_by: 128
  masked_softmax_fusion: true
  max_position_embeddings: 8192
  mcore_gpt: true
  megatron_amp_O2: true
  micro_batch_size: 1
  native_amp_growth_interval: 1000
  native_amp_init_scale: 4294967296
  normalization: rmsnorm
  normalize_attention_scores: true
  nsys_profile:
    enabled: false
    end_step: 10
    gen_shape: false
    ranks:
    - 0
    start_step: 10
    trace:
    - nvtx
    - cuda
  num_attention_heads: 32
  num_layers: 32
  num_micro_batches_with_partial_activation_checkpoints: null
  num_query_groups: 8
  onnx_safe: false
  openai_gelu: false
  optim:
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    contiguous_grad_buffer: true
    contiguous_param_buffer: true
    lr: 1e-4
    name: distributed_fused_adam
    overlap_grad_sync: true
    overlap_param_sync: true
    sched:
      constant_steps: 0
      min_lr: 1e-5
      name: CosineAnnealing
      warmup_steps: 500
    weight_decay: 0.1
  persist_layer_norm: true
  pipeline_model_parallel_size: 1
  position_embedding_type: rope
  post_process: true
  pre_process: true
  rampup_batch_size: null
  resume_from_checkpoint: null
  rotary_percentage: 1.0
  seed: 1234
  sequence_parallel: false
  share_embeddings_and_output_weights: false
  sync_batch_comm: false
  tensor_model_parallel_size: 4
  tokenizer:
    delimiter: null
    library: sentencepiece
    merge_file: null
    model: ${data_dir}/tokenizer/tokenizer.model
    sentencepiece_legacy: false
    type: null
    vocab_file: ${data_dir}/tokenizer/tokenizer.vocab
  transformer_block_type: pre_ln
  transformer_engine: true
  ub_tp_comm_overlap: false
  use_cpu_initialization: false
  use_flash_attention: true
  use_scaled_init_method: true
  virtual_pipeline_model_parallel_size: null
run:
  dependency: singleton
  name: llama_8b_16nodes_tp_4_pp_1_cp_1_ep_1_mbs_1_act_ckpt_None_num_mbs_act_None_act_per_pipe_None
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-0:30:00
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  enable_checkpointing: false
  gradient_clip_val: 1.0
  limit_test_batches: 1
  limit_val_batches: 1
  log_every_n_steps: 1
  logger: false
  max_epochs: null
  max_steps: 50
  max_time: '5:23:30:00'
  num_nodes: 16
  precision: bf16
  use_distributed_sampler: false
  val_check_interval: 50
